fmod BOOLEAN issort Boolean .ops true false : -> Boolean [ctor] .op not_ : Boolean -> Boolean [prec 53] .op _and_ : Boolean Boolean -> Boolean [prec 55] .
op _or_ : Boolean Boolean -> Boolean [prec 57] .var B : Boolean .
*** Define the addition function recursively:
eq not true = false .
eq not false = true .
eq true and B = B .
eq false and B = false .
eq true or B = true .
eq false or B = B .endfm